[package]
name = "icegen"
version = "0.1.0"
authors = ["Byeonggon Lee <gonny952@gmail.com>"]
edition = "2018"
build = "build.rs"
links = "cmark"
[dependencies]
walkdir = "2"
handlebars = "3"
libc = "0.2"
[build-dependencies]
bindgen = "0.53"
